### ISSUE TITLE
Feature Request:  Recognize Unicode Entities Numbered In Hex

### ISSUE THREAD

**Issue by peoppenheimer** [jessealama/ce-el#12]
The canonical presentation of Unicode entities at unicode.org is in hex.  It would be nice if ce-entities-name-numeric-entities() handled entities numbered in hex.  Alternatively, there could be a new ce-entities-name-hex-entities() function.

Currently, an attempt to find names for hex-numbered entities raises an error like this:

Debugger entered--Lisp error: (error "The string '&#x2129;' appears not to be an
entity.")
  signal(error ("The string '&#x2129;' appears not to be an entity."))
  error("The string '%s' appears not to be an entity." "&#x2129;")
  ce-entities-name-numeric-entities()
  call-interactively(ce-entities-name-numeric-entities t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)

Of course, if a numbered entity has no name, then it should be left alone.

**Comment by jessealama** [comment]
Thanks for the suggestion.  Can you give me a minimal file that displays this behavior?  Adding support for hexidecimal notation will be straightforward, but I'd like a nice test case to work with.

**Comment by peoppenheimer** [comment]
I will provide a test case.  Thanks for addressing this.  (Note that, amusingly, the Unicode entity in question in this example is correctly rendered by the github page we're on.  It's a turned Greek small iota.)

**Comment by jessealama** [comment]
At the moment ce-el already is "aware" of the hexidecimal code points for the entities defined by the XHTML standard.  But coverage of all Unicode characters, specifically, those that do not correspond to any named entity in the XHTML standard (such as the upturned small iota), will have to be a no-op (there's nothing to do).  But still, please do provide a minimal example and we can try it out.

**Comment by peoppenheimer** [comment]
Instead of a no-op it was an error.

**Comment by jessealama** [comment]
Can you give me a complete example, that is, an XHTML file which causes breakage?

## 

Jesse Alama

**Comment by peoppenheimer** [comment]
Here's one:

The error described in my original feature request is raised when the function hits the first occurrence of the hex code for the turned iota unicode entity.  A no-op on a non-xhtml char is a perfectly reasonable behavior.

**Comment by peoppenheimer** [comment]
I see that the file attachment seems not to show here in the github interface.   What is the approved method for communicating a test file to a github project?

(You should have the file anyway, because I cc'ed it to your personal address.  If you don't have it, please let me know.)

**Comment by jessealama** [comment]
Fence the example in with four consecutive back ticks at the beginning of their own lines.

## 

Jesse Alama

**Comment by peoppenheimer** [comment]
Do you mean that each line of the example must begin with four consecutive back ticks?

**Comment by jessealama** [comment]
The content between the four-backticked lines will be rendered as code.

## 

Jesse Alama

**Comment by peoppenheimer** [comment]
Ah.  So I put a line with nothing but four back ticks, and then a code block, and then a line with nothing but four back ticks.

Is that right?

**Comment by jessealama** [comment]
Yeah: http://github.github.com/github-flavored-markdown/

## 

Jesse Alama

**Comment by jessealama** [comment]
Is this what you mean?

```
<html><head><title></title></head><body>&#xabcd;</body></html>
```

(I know this isn't strictly speaking a valid XHTML file.  I'm just trying to understand what you have in mind.)

**Comment by peoppenheimer** [comment]
Yep.  The canonical listing of unicode characters, if I understand the Unicode standard correctly, is in the form 
U+xxxx, where the exes represent hex digits.  At least, when I look up Unicode character codes, I usually come across the hex form first.  So, yeah: &#xF0A3; would be an example of what I want.

Again, a no-op on these, when they are not named xhtml entities is perfectly appropriate -- but not an error.

**Comment by jessealama** [comment]
OK.  I see that such things are not simply ignored, but apparently deleted.  I'm on it.

**Comment by jessealama** [comment]
I'm still waiting for a complete (but minimal) example of the input you're working with.  You can use either the box or the upside down iota.  Use the four backticks convention to include your example here in GitHub.

**Comment by peoppenheimer** [comment]
```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<title>Example of hex character code</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body>

<h1>Example of hex character code</h1>

 (&#x2129;<i>x</i>)(<i>fx</i> &amp; <i>x</i>=<i>a</i>)

</body>

</html>

```

**Comment by jessealama** [comment]
OK, thanks -- I see that the dash inspector doesn't do the right thing here.  I'm on it.

**Comment by jessealama** [comment]
It seems that the current version of the dash editor recognizes this particular entity as a valid Unicode character, and simply maps the "&#x2129;" into the actual inverted iota character.  Perhaps that _is_ the right thing to do?

**Comment by jessealama** [comment]
This is now fixed.
