### ISSUE TITLE
ce-dash doesn't recognize Roman numeral numeric ranges.

### ISSUE THREAD

**Issue by jessealama** [jessealama/ce-el#8]
For example, in

```
i-iii, I-IV, and XLV-LVI
```

these are all numeric ranges, and should be replaced by endashes.

**Comment by peoppenheimer** [comment]
There are also some more complicated ranges, for instance with citations of some ancient sources, such as:

_Politics_ VII.4.1325b40–1365a5.

In addition, biographical ranges require special handling if there are letters or other characters interposed, as in:

b. 1987- d. 2012

6/5 BCE-38/39 CE
